'use strict';

import { filterForecast, checkTemperatureBelowForecasts, findMinTemperature } from '../../forecastUtil.mjs';
import { expect } from 'chai';
import moment from 'moment';

describe('Tests Filter Forecast', function () {
    it('verifies successful filter by date', async () => {
        
        const forecasts = createForecasts();

        const date = moment('2024-03-30');

        const result = filterForecast(forecasts, date);

        expect(result).to.be.an('array');
        expect(result).to.have.lengthOf(23)
    });
});



describe('Tests Temperature Below Forecast', function () {
    it('verifies successful filter by temperature below', async () => {
        
        const forecasts = createForecasts();

        const result = checkTemperatureBelowForecasts(forecasts, 20);

        expect(result).to.be.an('array');
        expect(result).to.have.lengthOf(1)
        expect(result[0].values.temperature).to.be.lessThan(20)
    });
});

describe('findMinTemperature', function () {
    it('Get min temp of an array', async () => {
        
        const forecasts = [
            {
                "time": "2024-03-30T05:00:00Z",
                "values": {
                    "temperature": 23.64
                }
            },
            {
                "time": "2024-03-30T06:00:00Z",
                "values": {
                    "temperature": 19
                }
            },
            {
                "time": "2024-03-30T07:00:00Z",
                "values": {
                    "temperature": 24.64
                }
            }
        ]

        const result = findMinTemperature(forecasts);

        expect(result).to.be.an('object');
        expect(result.values.temperature).to.be.equal(19)
    });
});


const createForecasts = () => {
    return [
    {
        "time": "2024-03-30T05:00:00Z",
        "values": {
            "cloudBase": 2.46,
            "cloudCeiling": null,
            "cloudCover": 86.81,
            "dewPoint": 21.41,
            "evapotranspiration": 0.018,
            "freezingRainIntensity": 0,
            "humidity": 82.25,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 990.21,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0,
            "rainIntensity": 0,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 24.64,
            "temperatureApparent": 24.64,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 24.13,
            "weatherCode": 1001,
            "windDirection": 220.15,
            "windGust": 0.9,
            "windSpeed": 0.7
        }
    },
    {
        "time": "2024-03-30T06:00:00Z",
        "values": {
            "cloudBase": 2.46,
            "cloudCeiling": null,
            "cloudCover": 89.06,
            "dewPoint": 21.34,
            "evapotranspiration": 0.022,
            "freezingRainIntensity": 0,
            "humidity": 82.79,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 989.63,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0,
            "rainIntensity": 0,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 24.46,
            "temperatureApparent": 24.46,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 24.14,
            "weatherCode": 1001,
            "windDirection": 306.39,
            "windGust": 1.05,
            "windSpeed": 1.05
        }
    },
    {
        "time": "2024-03-30T07:00:00Z",
        "values": {
            "cloudBase": 4.62,
            "cloudCeiling": null,
            "cloudCover": 92.86,
            "dewPoint": 21.29,
            "evapotranspiration": 0.025,
            "freezingRainIntensity": 0,
            "humidity": 83.74,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 989.52,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0,
            "rainIntensity": 0,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 24.22,
            "temperatureApparent": 24.22,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 24.14,
            "weatherCode": 1001,
            "windDirection": 236.78,
            "windGust": 1.42,
            "windSpeed": 1.42
        }
    },
    {
        "time": "2024-03-30T08:00:00Z",
        "values": {
            "cloudBase": 4.83,
            "cloudCeiling": null,
            "cloudCover": 95.81,
            "dewPoint": 21.26,
            "evapotranspiration": 0.024,
            "freezingRainIntensity": 0,
            "humidity": 84.66,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 989.7,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0,
            "rainIntensity": 0,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 24.01,
            "temperatureApparent": 24.01,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 24.14,
            "weatherCode": 1001,
            "windDirection": 68.63,
            "windGust": 1.45,
            "windSpeed": 1.45
        }
    },
    {
        "time": "2024-03-30T09:00:00Z",
        "values": {
            "cloudBase": 5.05,
            "cloudCeiling": null,
            "cloudCover": 97.07,
            "dewPoint": 21.27,
            "evapotranspiration": 0.025,
            "freezingRainIntensity": 0,
            "humidity": 85.04,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 990.25,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0,
            "rainIntensity": 0,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 23.94,
            "temperatureApparent": 23.94,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 24.13,
            "weatherCode": 1001,
            "windDirection": 322.1,
            "windGust": 1.61,
            "windSpeed": 1.61
        }
    },
    {
        "time": "2024-03-30T10:00:00Z",
        "values": {
            "cloudBase": 5.07,
            "cloudCeiling": null,
            "cloudCover": 97.77,
            "dewPoint": 21.32,
            "evapotranspiration": 0.025,
            "freezingRainIntensity": 0,
            "humidity": 85.89,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 990.75,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0,
            "rainIntensity": 0,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 23.83,
            "temperatureApparent": 23.83,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 24.13,
            "weatherCode": 1001,
            "windDirection": 317.5,
            "windGust": 1.79,
            "windSpeed": 1.76
        }
    },
    {
        "time": "2024-03-30T11:00:00Z",
        "values": {
            "cloudBase": 5.01,
            "cloudCeiling": null,
            "cloudCover": 98.24,
            "dewPoint": 21.77,
            "evapotranspiration": 0.072,
            "freezingRainIntensity": 0,
            "humidity": 80.47,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 991.36,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0,
            "rainIntensity": 0,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 25.37,
            "temperatureApparent": 25.37,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 24.13,
            "weatherCode": 1001,
            "windDirection": 319.52,
            "windGust": 2.87,
            "windSpeed": 1.83
        }
    },
    {
        "time": "2024-03-30T12:00:00Z",
        "values": {
            "cloudBase": 5,
            "cloudCeiling": null,
            "cloudCover": 98.5,
            "dewPoint": 21.85,
            "evapotranspiration": 0.214,
            "freezingRainIntensity": 0,
            "humidity": 70.14,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 991.95,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0,
            "rainIntensity": 0,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 27.79,
            "temperatureApparent": 30.28,
            "uvHealthConcern": 1,
            "uvIndex": 2,
            "visibility": 24.13,
            "weatherCode": 1001,
            "windDirection": 71.39,
            "windGust": 2.96,
            "windSpeed": 1.97
        }
    },
    {
        "time": "2024-03-30T13:00:00Z",
        "values": {
            "cloudBase": 4.81,
            "cloudCeiling": null,
            "cloudCover": 100,
            "dewPoint": 21.75,
            "evapotranspiration": 0.406,
            "freezingRainIntensity": 0,
            "humidity": 61.42,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 992.18,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0,
            "rainIntensity": 0,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 19.98,
            "temperatureApparent": 20.07,
            "uvHealthConcern": 2,
            "uvIndex": 5,
            "visibility": 24.14,
            "weatherCode": 1001,
            "windDirection": 19.64,
            "windGust": 3.09,
            "windSpeed": 2.14
        }
    },
    {
        "time": "2024-03-30T14:00:00Z",
        "values": {
            "cloudBase": 4.89,
            "cloudCeiling": null,
            "cloudCover": 95.91,
            "dewPoint": 21.52,
            "evapotranspiration": 0.574,
            "freezingRainIntensity": 0,
            "humidity": 54.28,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 991.85,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0,
            "rainIntensity": 0,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 31.89,
            "temperatureApparent": 35.22,
            "uvHealthConcern": 3,
            "uvIndex": 8,
            "visibility": 24.14,
            "weatherCode": 1001,
            "windDirection": 16.54,
            "windGust": 3.24,
            "windSpeed": 2.35
        }
    },
    {
        "time": "2024-03-30T15:00:00Z",
        "values": {
            "cloudBase": 4.89,
            "cloudCeiling": null,
            "cloudCover": 96.31,
            "dewPoint": 21.24,
            "evapotranspiration": 0.691,
            "freezingRainIntensity": 0,
            "humidity": 49.04,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 991.02,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0,
            "rainIntensity": 0,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 33.39,
            "temperatureApparent": 36.8,
            "uvHealthConcern": 3,
            "uvIndex": 9,
            "visibility": 24.13,
            "weatherCode": 1001,
            "windDirection": 10.8,
            "windGust": 3.08,
            "windSpeed": 2.33
        }
    },
    {
        "time": "2024-03-30T16:00:00Z",
        "values": {
            "cloudBase": 2.82,
            "cloudCeiling": 3.35,
            "cloudCover": 97.26,
            "dewPoint": 21,
            "evapotranspiration": 0.751,
            "freezingRainIntensity": 0,
            "humidity": 45.41,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 989.96,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0,
            "rainIntensity": 0,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 34.49,
            "temperatureApparent": 37.92,
            "uvHealthConcern": 3,
            "uvIndex": 8,
            "visibility": 24.13,
            "weatherCode": 1001,
            "windDirection": 239.02,
            "windGust": 2.74,
            "windSpeed": 2.33
        }
    },
    {
        "time": "2024-03-30T17:00:00Z",
        "values": {
            "cloudBase": 1.53,
            "cloudCeiling": 2.92,
            "cloudCover": 96.73,
            "dewPoint": 20.64,
            "evapotranspiration": 0.747,
            "freezingRainIntensity": 0,
            "humidity": 42.73,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 988.63,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0.04,
            "rainIntensity": 0,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 35.19,
            "temperatureApparent": 38.45,
            "uvHealthConcern": 2,
            "uvIndex": 5,
            "visibility": 24.14,
            "weatherCode": 1001,
            "windDirection": 269.68,
            "windGust": 2.51,
            "windSpeed": 2.39
        }
    },
    {
        "time": "2024-03-30T18:00:00Z",
        "values": {
            "cloudBase": 1.64,
            "cloudCeiling": 2.96,
            "cloudCover": 97.28,
            "dewPoint": 21.58,
            "evapotranspiration": 0.401,
            "freezingRainIntensity": 0,
            "humidity": 48.1,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 20,
            "pressureSurfaceLevel": 987.33,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0.05,
            "rainIntensity": 0.04,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 34.15,
            "temperatureApparent": 38.09,
            "uvHealthConcern": 1,
            "uvIndex": 3,
            "visibility": 24.13,
            "weatherCode": 1001,
            "windDirection": 346.58,
            "windGust": 2.54,
            "windSpeed": 2.16
        }
    },
    {
        "time": "2024-03-30T19:00:00Z",
        "values": {
            "cloudBase": 1.72,
            "cloudCeiling": 2.96,
            "cloudCover": 100,
            "dewPoint": 23,
            "evapotranspiration": 0.116,
            "freezingRainIntensity": 0,
            "humidity": 58.91,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 20,
            "pressureSurfaceLevel": 986.66,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0.02,
            "rainIntensity": 0.05,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 32.07,
            "temperatureApparent": 36.9,
            "uvHealthConcern": 1,
            "uvIndex": 2,
            "visibility": 24.14,
            "weatherCode": 1001,
            "windDirection": 262.01,
            "windGust": 1.85,
            "windSpeed": 1.64
        }
    },
    {
        "time": "2024-03-30T20:00:00Z",
        "values": {
            "cloudBase": 1.62,
            "cloudCeiling": 3.3,
            "cloudCover": 100,
            "dewPoint": 23.07,
            "evapotranspiration": 0.093,
            "freezingRainIntensity": 0,
            "humidity": 63.88,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 20,
            "pressureSurfaceLevel": 986.63,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0.02,
            "rainIntensity": 0.02,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 30.68,
            "temperatureApparent": 35.12,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 24.14,
            "weatherCode": 1001,
            "windDirection": 232.56,
            "windGust": 2.19,
            "windSpeed": 2.06
        }
    },
    {
        "time": "2024-03-30T21:00:00Z",
        "values": {
            "cloudBase": 1.56,
            "cloudCeiling": 3.32,
            "cloudCover": 100,
            "dewPoint": 22.33,
            "evapotranspiration": 0.059,
            "freezingRainIntensity": 0,
            "humidity": 62.79,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 25,
            "pressureSurfaceLevel": 986.79,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0.03,
            "rainIntensity": 0.02,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 30.22,
            "temperatureApparent": 33.87,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 23.34,
            "weatherCode": 1001,
            "windDirection": 185.94,
            "windGust": 1,
            "windSpeed": 1
        }
    },
    {
        "time": "2024-03-30T22:00:00Z",
        "values": {
            "cloudBase": 1.49,
            "cloudCeiling": 3.47,
            "cloudCover": 100,
            "dewPoint": 21.84,
            "evapotranspiration": 0.073,
            "freezingRainIntensity": 0,
            "humidity": 62.47,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 25,
            "pressureSurfaceLevel": 987,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0.03,
            "rainIntensity": 0.03,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 29.79,
            "temperatureApparent": 32.92,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 24.14,
            "weatherCode": 1001,
            "windDirection": 76.62,
            "windGust": 1.95,
            "windSpeed": 1.95
        }
    },
    {
        "time": "2024-03-30T23:00:00Z",
        "values": {
            "cloudBase": 1.48,
            "cloudCeiling": 3.48,
            "cloudCover": 100,
            "dewPoint": 22.19,
            "evapotranspiration": 0.061,
            "freezingRainIntensity": 0,
            "humidity": 66.41,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 30,
            "pressureSurfaceLevel": 987.47,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0.02,
            "rainIntensity": 0.03,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 29.09,
            "temperatureApparent": 32.27,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 24.13,
            "weatherCode": 1001,
            "windDirection": 72.54,
            "windGust": 1.8,
            "windSpeed": 1.8
        }
    },
    {
        "time": "2024-03-31T00:00:00Z",
        "values": {
            "cloudBase": 1.51,
            "cloudCeiling": 3.46,
            "cloudCover": 100,
            "dewPoint": 22.12,
            "evapotranspiration": 0.036,
            "freezingRainIntensity": 0,
            "humidity": 66.51,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 30,
            "pressureSurfaceLevel": 988.31,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0.29,
            "rainIntensity": 0.02,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 28.98,
            "temperatureApparent": 32.06,
            "uvHealthConcern": 0,
            "uvIndex": 0,
            "visibility": 23.33,
            "weatherCode": 1001,
            "windDirection": 111.52,
            "windGust": 1.35,
            "windSpeed": 1.02
        }
    },
    {
        "time": "2024-03-31T01:00:00Z",
        "values": {
            "cloudBase": 1.82,
            "cloudCeiling": 3.34,
            "cloudCover": 93.62,
            "dewPoint": 22.3,
            "evapotranspiration": 0.026,
            "freezingRainIntensity": 0,
            "humidity": 72.03,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 30,
            "pressureSurfaceLevel": 989.09,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0.18,
            "rainIntensity": 0.29,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 27.85,
            "temperatureApparent": 30.63,
            "visibility": 24.14,
            "weatherCode": 4000,
            "windDirection": 104.04,
            "windGust": 1.54,
            "windSpeed": 0.76
        }
    },
    {
        "time": "2024-03-31T02:00:00Z",
        "values": {
            "cloudBase": 2.01,
            "cloudCeiling": null,
            "cloudCover": 86.3,
            "dewPoint": 22.38,
            "evapotranspiration": 0.03,
            "freezingRainIntensity": 0,
            "humidity": 74.42,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 30,
            "pressureSurfaceLevel": 989.58,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0.12,
            "rainIntensity": 0.18,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 27.36,
            "temperatureApparent": 29.95,
            "visibility": 24.13,
            "weatherCode": 1001,
            "windDirection": 99.25,
            "windGust": 1.43,
            "windSpeed": 1.09
        }
    },
    {
        "time": "2024-03-31T03:00:00Z",
        "values": {
            "cloudBase": 2.08,
            "cloudCeiling": null,
            "cloudCover": 83.22,
            "dewPoint": 22.42,
            "evapotranspiration": 0.025,
            "freezingRainIntensity": 0,
            "humidity": 76.3,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 30,
            "pressureSurfaceLevel": 989.49,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0.09,
            "rainIntensity": 0.12,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 26.97,
            "temperatureApparent": 29.33,
            "visibility": 24.13,
            "weatherCode": 1001,
            "windDirection": 69.27,
            "windGust": 1.1,
            "windSpeed": 0.87
        }
    },
    {
        "time": "2024-03-31T04:00:00Z",
        "values": {
            "cloudBase": 2.12,
            "cloudCeiling": null,
            "cloudCover": 86.54,
            "dewPoint": 22.33,
            "evapotranspiration": 0.026,
            "freezingRainIntensity": 0,
            "humidity": 77.23,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 30,
            "pressureSurfaceLevel": 989.14,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0.07,
            "rainIntensity": 0.09,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 26.67,
            "temperatureApparent": 28.83,
            "visibility": 24.13,
            "weatherCode": 1001,
            "windDirection": 95.39,
            "windGust": 1.21,
            "windSpeed": 1.01
        }
    },
    {
        "time": "2024-03-31T05:00:00Z",
        "values": {
            "cloudBase": 2.14,
            "cloudCeiling": null,
            "cloudCover": 85.49,
            "dewPoint": 22.22,
            "evapotranspiration": 0.029,
            "freezingRainIntensity": 0,
            "humidity": 79.72,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 25,
            "pressureSurfaceLevel": 988.7,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0.06,
            "rainIntensity": 0.07,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 26.01,
            "temperatureApparent": 26.01,
            "visibility": 24.13,
            "weatherCode": 1001,
            "windDirection": 340.33,
            "windGust": 1.44,
            "windSpeed": 1.44
        }
    },
    {
        "time": "2024-03-31T06:00:00Z",
        "values": {
            "cloudBase": 2.14,
            "cloudCeiling": null,
            "cloudCover": 80.68,
            "dewPoint": 22.1,
            "evapotranspiration": 0.028,
            "freezingRainIntensity": 0,
            "humidity": 81.35,
            "iceAccumulation": 0,
            "precipitationProbability": 25,
            "pressureSurfaceLevel": 988.28,
            "rainAccumulation": 0,
            "rainIntensity": 0.06,
            "sleetAccumulation": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowIntensity": 0,
            "temperature": 25.54,
            "temperatureApparent": 25.54,
            "visibility": 24.13,
            "weatherCode": 1001,
            "windDirection": 330.42,
            "windGust": 1.46,
            "windSpeed": 1.45
        }
    },
    {
        "time": "2024-03-31T07:00:00Z",
        "values": {
            "cloudBase": 2.14,
            "cloudCeiling": null,
            "cloudCover": 64.66,
            "dewPoint": 22.03,
            "evapotranspiration": 0.026,
            "freezingRainIntensity": 0,
            "humidity": 82.42,
            "iceAccumulation": 0,
            "precipitationProbability": 25,
            "pressureSurfaceLevel": 988.38,
            "rainAccumulation": 0,
            "rainIntensity": 0.06,
            "sleetAccumulation": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowIntensity": 0,
            "temperature": 25.26,
            "temperatureApparent": 25.26,
            "visibility": 24.14,
            "weatherCode": 1102,
            "windDirection": 330.42,
            "windGust": 1.44,
            "windSpeed": 1.39
        }
    },
    {
        "time": "2024-03-31T08:00:00Z",
        "values": {
            "cloudBase": 4.98,
            "cloudCeiling": null,
            "cloudCover": 48.65,
            "dewPoint": 21.97,
            "evapotranspiration": 0.024,
            "freezingRainIntensity": 0,
            "humidity": 83.49,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 988.48,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0,
            "rainIntensity": 0,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 24.98,
            "temperatureApparent": 24.98,
            "visibility": 24.14,
            "weatherCode": 1101,
            "windDirection": 340.05,
            "windGust": 1.43,
            "windSpeed": 1.33
        }
    },
    {
        "time": "2024-03-31T09:00:00Z",
        "values": {
            "cloudBase": 4.98,
            "cloudCeiling": null,
            "cloudCover": 32.64,
            "dewPoint": 21.91,
            "evapotranspiration": 0.022,
            "freezingRainIntensity": 0,
            "humidity": 84.56,
            "iceAccumulation": 0,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 988.58,
            "rainAccumulation": 0,
            "rainIntensity": 0,
            "sleetAccumulation": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowIntensity": 0,
            "temperature": 24.7,
            "temperatureApparent": 24.7,
            "visibility": 24.14,
            "weatherCode": 1100,
            "windDirection": 340.05,
            "windGust": 1.42,
            "windSpeed": 1.27
        }
    },
    {
        "time": "2024-03-31T10:00:00Z",
        "values": {
            "cloudBase": 4.98,
            "cloudCeiling": null,
            "cloudCover": 34.27,
            "dewPoint": 22.11,
            "evapotranspiration": 0.051,
            "freezingRainIntensity": 0,
            "humidity": 79.92,
            "iceAccumulation": 0,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 989.3,
            "rainAccumulation": 0,
            "rainIntensity": 0,
            "sleetAccumulation": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowIntensity": 0,
            "temperature": 25.91,
            "temperatureApparent": 25.91,
            "visibility": 24.14,
            "weatherCode": 1100,
            "windDirection": 340.05,
            "windGust": 1.65,
            "windSpeed": 1.39
        }
    },
    {
        "time": "2024-03-31T11:00:00Z",
        "values": {
            "cloudBase": 4.95,
            "cloudCeiling": null,
            "cloudCover": 35.9,
            "dewPoint": 22.3,
            "evapotranspiration": 0.08,
            "freezingRainIntensity": 0,
            "humidity": 75.28,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 990.01,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0,
            "rainIntensity": 0,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 27.13,
            "temperatureApparent": 29.56,
            "visibility": 24.14,
            "weatherCode": 1100,
            "windDirection": 7.49,
            "windGust": 1.87,
            "windSpeed": 1.51
        }
    },
    {
        "time": "2024-03-31T12:00:00Z",
        "values": {
            "cloudBase": 4.95,
            "cloudCeiling": null,
            "cloudCover": 37.54,
            "dewPoint": 22.49,
            "evapotranspiration": 0.109,
            "freezingRainIntensity": 0,
            "humidity": 70.65,
            "iceAccumulation": 0,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 990.72,
            "rainAccumulation": 0,
            "rainIntensity": 0,
            "sleetAccumulation": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowIntensity": 0,
            "temperature": 28.34,
            "temperatureApparent": 31.44,
            "visibility": 24.14,
            "weatherCode": 1101,
            "windDirection": 7.49,
            "windGust": 2.1,
            "windSpeed": 1.63
        }
    },
    {
        "time": "2024-03-31T13:00:00Z",
        "values": {
            "cloudBase": 4.95,
            "cloudCeiling": null,
            "cloudCover": 33.52,
            "dewPoint": 22.22,
            "evapotranspiration": 0.264,
            "freezingRainIntensity": 0,
            "humidity": 63.01,
            "iceAccumulation": 0,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 990.46,
            "rainAccumulation": 0,
            "rainIntensity": 0,
            "sleetAccumulation": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowIntensity": 0,
            "temperature": 30.35,
            "temperatureApparent": 34.18,
            "visibility": 24.14,
            "weatherCode": 1100,
            "windDirection": 7.49,
            "windGust": 2.01,
            "windSpeed": 1.6
        }
    },
    {
        "time": "2024-03-31T14:00:00Z",
        "values": {
            "cloudBase": 4.92,
            "cloudCeiling": null,
            "cloudCover": 29.5,
            "dewPoint": 21.95,
            "evapotranspiration": 0.42,
            "freezingRainIntensity": 0,
            "humidity": 55.38,
            "iceAccumulation": 0,
            "iceAccumulationLwe": 0,
            "precipitationProbability": 0,
            "pressureSurfaceLevel": 990.2,
            "rainAccumulation": 0,
            "rainAccumulationLwe": 0,
            "rainIntensity": 0,
            "sleetAccumulation": 0,
            "sleetAccumulationLwe": 0,
            "sleetIntensity": 0,
            "snowAccumulation": 0,
            "snowAccumulationLwe": 0,
            "snowIntensity": 0,
            "temperature": 32.35,
            "temperatureApparent": 36.49,
            "visibility": 24.13,
            "weatherCode": 1100,
            "windDirection": 344.09,
            "windGust": 1.91,
            "windSpeed": 1.56
        }
    }
]
}