on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: 'Create env file'
        run: touch .env
      - name: 'Write env file content'
        run:
          echo WEATHER_API=${{ secrets.WEATHER_API }} >> .env
          echo WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }} >> .env
          echo WEATHER_API_HOST=${{ secrets.WEATHER_API_HOST }} >> .env
      - name: 'Show env file'
        run: cat .env
      - run: sam build --use-container --template ./weather-app-function/template.yaml
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-file ./weather-app-function/samconfig.toml 